jobs:
  include:
    - stage: deploy
      name: "Python 3.8 on Windows"
      os: windows    
      language: shell
      before_install:
        - choco install python --version=3.8.3
        - choco install innosetup
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
      install:
        - pip install -r requirements.txt
        - pip install pyinstaller
      script:
        - pyinstaller rss-tube.spec
        - iscc rss-tube.iss
        - mv "inno-output\rsstube-installer.exe" "rsstube-installer-win.exe"
      deploy:
        provider: releases
        edge: true
        cleanup: false
        api_key: $GITHUB_TOKEN
        file: rsstube-installer-win.exe
        on:
          tags: true
    - stage: deploy
      name: "Python 3.8 on ubuntu focal"
      os: linux
      dist: focal
      language: python
      python: 3.8.3
      before_install:
        - pip install --upgrade pip
      install:
        - pip install -r requirements.txt
        - pip install pyinstaller
      script:
        - make build
        - cp dist/rsstube_amd64.deb rsstube_amd64_focal.deb
      deploy:
        provider: releases
        edge: true
        cleanup: false
        api_key: $GITHUB_TOKEN
        file: rsstube_amd64_focal.deb
        on:
          tags: true
